'use client';
import {useEffect,useRef,useState} from 'react';
import {GameCard} from './GameCard';
import {GameModal} from './GameModal';
export function SectionPage({category,title}){const [items,setItems]=useState([]),[cursor,setCursor]=useState(0),[done,setDone]=useState(false),[loading,setLoading]=useState(false),[provider,setProvider]=useState('all'),[providers,setProviders]=useState([]),[mode,setMode]=useState('real'),[selected,setSelected]=useState(null),[launch,setLaunch]=useState(null);const sentinel=useRef(null);
 useEffect(()=>{fetch('/api/providers').then(r=>r.json()).then(x=>setProviders(x.providers||[]))},[]);
 useEffect(()=>{setItems([]);setCursor(0);setDone(false)},[category,provider]);
 useEffect(()=>{if(done||loading)return;const io=new IntersectionObserver(es=>es[0].isIntersecting&&load(),{rootMargin:'900px'});if(sentinel.current)io.observe(sentinel.current);return()=>io.disconnect()},[cursor,done,loading,provider,category]);
 async function load(){setLoading(true);try{const q=new URLSearchParams({category,cursor,limit:24,provider});const d=await fetch('/api/catalog?'+q).then(r=>r.json());setItems(a=>{const ids=new Set(a.map(x=>x.id));return [...a,...d.items.filter(x=>!ids.has(x.id))]});setCursor(d.nextCursor??cursor);setDone(d.nextCursor===null)}finally{setLoading(false)}}
 async function play(game){setSelected(game);setLaunch({loading:true});try{const response=await fetch('/api/launch?gameId='+encodeURIComponent(game.id)+'&mode='+mode);const data=await response.json();if(!response.ok)throw new Error(data.error||'The game could not be launched.');setLaunch(data)}catch(error){setLaunch({error:error.message||'The game could not be launched.'})}}
 return <section><div className="pagehead"><div><div className="eyebrow">LIVE BACKEND CATALOG</div><h1>{title}</h1><p className="muted">Provider data, filtering, infinite loading and in-page game launch.</p></div><div className="filters"><select value={provider} onChange={e=>setProvider(e.target.value)}><option value="all">All providers</option>{providers.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={mode} onChange={e=>setMode(e.target.value)}><option value="real">Real mode</option><option value="fun">Demo mode</option></select></div></div><div className="grid">{items.map(g=><GameCard key={g.id} game={g} onPlay={play}/>)}</div><div ref={sentinel} className="sentinel">{loading?'Loading games…':done?'All available games loaded.':'Scroll to load more.'}</div>{selected&&<GameModal game={selected} mode={mode} url={launch?.url} error={launch?.error} loading={launch?.loading} onClose={()=>{setSelected(null);setLaunch(null)}}/>}</section>}
